// Public, attributed research only. Never commit private consultation material.
export const SNAPSHOT_DATE = '08 OCT 2026';

export const sources = [
  { id: 'AMD25', owner: 'AMD Investor Relations', title: 'AMD Q4 and full-year 2025 financial results', date: '03 Feb 2026', kind: 'Company financials', trust: 'Primary', url: 'https://ir.amd.com/news-events/press-releases/detail/1276/amd-reports-fourth-quarter-and-full-year-2025-financial-results', insight: 'AMD 2025 data-center revenue was $16.6B, up 32% YoY; this segment contains EPYC CPUs and Instinct GPUs. Not a CPU-only number.' },
  { id: 'AMD6', owner: 'AMD', title: '6th Gen EPYC 9006 Venice architecture', date: '23 Jul 2026', kind: 'Product architecture', trust: 'Vendor claim', url: 'https://www.amd.com/en/blogs/2026/agentic-ai-amd-epyc-9005-cpus-wins-today-epyc-9006.html', insight: 'AMD documents EPYC 9006 / Venice with up to 256 cores/socket, 16 DDR5 channels, and PCIe Gen 6; verify SKU-specific availability and real workload performance.' },
  { id: 'AMD6RAMP', owner: 'AMD Newsroom', title: 'Venice 2nm production ramp announced', date: '21 May 2026', kind: 'Supply / process', trust: 'Vendor claim', url: 'https://newsroom.amd.com/news/amd-announces-production-ramp-of-next-generation-a/', insight: 'AMD announced a 6th Gen EPYC production ramp on TSMC 2nm; production ramp is not independently verified unit availability.' },
  { id: 'AMD24', owner: 'AMD', title: '5th Gen EPYC 9005 / Turin launch', date: '10 Oct 2024', kind: 'Product launch', trust: 'Vendor claim', url: 'https://www.amd.com/en/newsroom/press-releases/2024-10-10-amd-launches-5th-gen-amd-epyc-cpus-maintaining-le.html', insight: 'Published EPYC 9005 configurations span 8–192 cores, with Zen 5 and Zen 5c options. Performance claims require workload-level validation.' },
  { id: 'INTEL25', owner: 'Intel Newsroom', title: 'Xeon 6 launch overview', date: '24 Feb 2025', kind: 'Product launch', trust: 'Vendor claim', url: 'https://newsroom.intel.com/data-center/intel-unveils-leadership-ai-networking-solutions-xeon-6-processors', insight: 'The Xeon 6 portfolio targets different workloads with P-core and E-core variants.' },
  { id: 'INTEL6PLUS', owner: 'Intel', title: 'Xeon 6+ product family / 18A', date: 'Q2 2026', kind: 'Product specifications', trust: 'Primary', url: 'https://www.intel.com/content/www/us/en/products/details/processors/xeon/6-plus-series.html', insight: 'Xeon 6+ E-core configurations listed through 288 cores per socket; a product-spec maximum, not a cross-vendor performance measure.' },
  { id: 'INTELAI', owner: 'Intel Newsroom', title: 'Xeon 6 for GPU-accelerated AI systems', date: '22 May 2025', kind: 'AI infrastructure', trust: 'Vendor claim', url: 'https://www.intel.com/content/www/us/en/newsroom/news/artificial-intelligence/new-intel-xeon-6-cpus-maximize-gpu-ai-performance.html', insight: 'CPU responsibilities in GPU systems include orchestration, data movement and host-side work; CPU demand cannot be inferred from GPU shipments alone.' },
  { id: 'INTEL26', owner: 'Intel', title: 'Xeon 6 architecture: P-cores and E-cores', date: '24 Feb 2026 reviewed', kind: 'Product reference', trust: 'Primary', url: 'https://www.intel.com/content/www/us/en/support/articles/000098612/processors/intel-xeon-processors.html', insight: 'Intel describes differentiated P-core and E-core families for compute-intensive versus scale-out efficiency workloads.' },
  { id: 'AZUREAMD', owner: 'AMD Newsroom', title: 'Microsoft / AMD expanded Azure collaboration', date: '20 Jul 2026', kind: 'Customer / adoption', trust: 'Vendor claim', url: 'https://newsroom.amd.com/news/microsoft-azure-ai-infrastructure/', insight: 'The partners announced two planned 6th Gen EPYC-based Azure VM offerings. An announcement does not establish deployed fleet volume.' },
  { id: 'ARM', owner: 'Arm Learning Paths', title: 'Arm Neoverse cloud inference environments', date: 'Accessed Oct 2026', kind: 'Ecosystem reference', trust: 'Primary', url: 'https://learn.arm.com/learning-paths/servers-and-cloud-computing/ai-portal-cloud-text-to-text/1-setup/', insight: 'Arm’s cloud CPU ecosystem includes AWS Graviton4, Google Axion and Azure Cobalt 100. These are Arm alternatives, not x86 parts.' },
];

export const competitors = [
  { id: 'amd', name: 'AMD', product: 'EPYC', mark: 'A', category: 'x86 · challenger', tone: 'mint', headline: 'Density + system-level throughput', summary: '6th Gen Venice extends the EPYC roadmap with higher published core density and memory/I/O capabilities.', strength: ['High-density server configurations', 'Venice 9006 published 256-core ceiling', 'Multi-vendor server ecosystem'], watch: ['Workload-specific performance proof', 'Customer switching costs', 'Pricing and supply verification'], sources: ['AMD6','AMD6RAMP','AMD25'] },
  { id: 'intel', name: 'Intel', product: 'Xeon', mark: 'I', category: 'x86 · incumbent', tone: 'blue', headline: 'Installed base + platform breadth', summary: 'Competes through a very large software/server footprint, platform features, and P-/E-core portfolio segmentation.', strength: ['Broad enterprise installed base', 'Xeon 6+ E-core density up to 288', 'Integrated accelerators and ecosystem'], watch: ['Competitive TCO by workload', 'Migration incentives', 'Actual realized pricing'], sources: ['INTEL6PLUS','INTEL25','INTEL26'] },
  { id: 'arm', name: 'Arm ecosystem', product: 'Neoverse / custom', mark: 'N', category: 'ARM64 · adjacency', tone: 'violet', headline: 'Cloud-native efficiency + custom silicon', summary: 'Not x86, but increasingly relevant to hyperscale procurement and workload-portability decisions.', strength: ['Hyperscaler-specific integration', 'Performance-per-watt focus', 'Cloud-native scale-out positioning'], watch: ['Binary/software compatibility', 'Application portability', 'Ownership vs merchant CPU choices'], sources: ['ARM'] }
];

export const workloads = [
  { id: 'cloud', label: 'Cloud-native', icon: 'cloud', theme: 'Throughput at scale', question: 'How many useful transactions can fit within a power and infrastructure budget?', metrics: ['Performance / watt', 'Core density', 'Fleet-level operability'], buyer: 'Hyperscaler, cloud platform', insight: 'Fleet economics and reproducible scale-out benchmarks tend to matter more than a single headline clock speed.' },
  { id: 'enterprise', label: 'Enterprise', icon: 'building', theme: 'Compatibility + consolidation', question: 'Can we modernize servers without creating software or operational risk?', metrics: ['Software licensing', 'Migration effort', 'Virtualization density'], buyer: 'Enterprise IT and OEM/channel', insight: 'Software licenses, validated configurations and installed-base friction can dominate the acquisition-price difference.' },
  { id: 'hpc', label: 'HPC / simulation', icon: 'cpu', theme: 'Workload-dependent throughput', question: 'What wins on our exact application, memory and network configuration?', metrics: ['Memory bandwidth', 'Vector / compute path', 'Interconnect efficiency'], buyer: 'Research, engineering, laboratories', insight: 'End-to-end application tests outrank synthetic peak performance; memory and interconnect can be limiting.' },
  { id: 'ai', label: 'AI infrastructure', icon: 'brain', theme: 'Keep accelerators busy', question: 'Is the CPU executing inference, feeding accelerators, or coordinating the system?', metrics: ['CPU task mix', 'Data movement', 'Host-to-GPU balance'], buyer: 'AI cloud, hyperscaler, enterprise AI', insight: 'CPU-only inference and GPU-host functions are different markets. Measure utilization and bottlenecks separately.' },
];

export const aiPaths = [
  { id: 'cpu', n:'01', label:'CPU-only inference', tag:'MODEL EXECUTION', title:'The CPU runs the model.', statement:'Small, quantized or latency-sensitive models can be practical on CPU depending on model size, memory and economics.', bottleneck:'Benchmark tokens/sec, tail latency, RAM bandwidth and cost per request.', caution:'Do not equate vendor peak TOPS with production model throughput.' },
  { id: 'host', n:'02', label:'GPU host CPU', tag:'ACCELERATOR ENABLER', title:'The CPU keeps GPUs productive.', statement:'CPU cores handle scheduling, preprocessing, storage/network IO, orchestration and parts of serving pipelines.', bottleneck:'Measure data starvation, CPU saturation, IO limits and GPU idle time.', caution:'GPU demand does not map one-to-one onto CPU units or CPU revenue.' },
  { id: 'data', n:'03', label:'Retrieval + data', tag:'PIPELINE ECONOMICS', title:'The CPU moves and prepares context.', statement:'Embedding preparation, retrieval, indexing, ETL and networking can all create substantial non-GPU compute demand.', bottleneck:'End-to-end throughput, memory footprint, network and storage costs.', caution:'AI infrastructure demand is multi-layered; segment before forecasting.' },
];

export const strategicQuestions = [
  { q:'Who really competes?', a:'Intel Xeon and AMD EPYC compete directly in x86 servers. Arm-based cloud processors compete for some of the same application budgets, especially where workloads are portable. Compare at the deployment level, not just CPU architecture.', source:'INTEL25' },
  { q:'Where does share shift first?', a:'An adoption hypothesis: hyperscalers can migrate or optimize specific fleet workloads faster than heterogeneous enterprise estates. Validate with public instance catalogs, OEM platform availability and independently sourced shipment data. No verified share number is included in this starter.', source:'AMD24' },
  { q:'Why is server pricing opaque?', a:'Published list prices differ from negotiated transaction prices. OEM bundling, multi-year agreements, platform qualification, volumes, warranties and software licensing can dominate realized cost. Treat list prices as references, not ASPs.', source:'AMD24' },
  { q:'Does AI automatically lift CPU demand?', a:'No. AI expands some CPU workloads but may consolidate others. Separate CPU-only model execution, accelerator host systems, and retrieval/data processing; quantify each independently.', source:'INTELAI' },
  { q:'What would change a purchase decision?', a:'Run representative workloads on realistic server configurations. Compare software compatibility, usable performance, procurement terms, energy, cooling and operational risk over the same time horizon.', source:'INTEL26' },
];

export const glossary = [
  ['ASP', 'Average selling price; an observed realized selling price, not an online list price.'],
  ['CPU socket', 'Physical processor package location in a server. Core count and socket count are different measures.'],
  ['EPYC', 'AMD family of server CPUs.'],
  ['Xeon', 'Intel family of server CPUs.'],
  ['P-core / E-core', 'Intel performance-oriented versus efficiency-oriented core families; compare the actual Xeon SKU.'],
  ['TCO', 'Total cost of ownership, including hardware, electricity, software and operations over time.'],
  ['PUE', 'Power Usage Effectiveness; total data-center energy divided by IT energy.'],
  ['Hyperscaler', 'Operator of very large-scale cloud or internet infrastructure.'],
  ['HPC', 'High-performance computing; large-scale scientific, engineering or simulation workloads.'],
  ['MNPI', 'Material non-public information; never contribute it to this public research project.'],
];